// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuTRYkGqTlVxfo7N2HPwJ6tGy1WHBDqhM',
    appId: '1:737705953982:web:c2babf0592790700dcecef',
    messagingSenderId: '737705953982',
    projectId: 'ttgo-f2421',
    authDomain: 'ttgo-f2421.firebaseapp.com',
    storageBucket: 'ttgo-f2421.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwnxNXLectPg9ks4jYmLnQB9Wxh43E610',
    appId: '1:737705953982:android:9ad7426da65b8defdcecef',
    messagingSenderId: '737705953982',
    projectId: 'ttgo-f2421',
    storageBucket: 'ttgo-f2421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiLlB50NkKqEJKdXX9aJeW9mleuWLn8Z4',
    appId: '1:737705953982:ios:ec45dc4d9fcdf091dcecef',
    messagingSenderId: '737705953982',
    projectId: 'ttgo-f2421',
    storageBucket: 'ttgo-f2421.firebasestorage.app',
    iosBundleId: 'com.example.ttgoInterface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiLlB50NkKqEJKdXX9aJeW9mleuWLn8Z4',
    appId: '1:737705953982:ios:ec45dc4d9fcdf091dcecef',
    messagingSenderId: '737705953982',
    projectId: 'ttgo-f2421',
    storageBucket: 'ttgo-f2421.firebasestorage.app',
    iosBundleId: 'com.example.ttgoInterface',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuTRYkGqTlVxfo7N2HPwJ6tGy1WHBDqhM',
    appId: '1:737705953982:web:0891c1966037b37bdcecef',
    messagingSenderId: '737705953982',
    projectId: 'ttgo-f2421',
    authDomain: 'ttgo-f2421.firebaseapp.com',
    storageBucket: 'ttgo-f2421.firebasestorage.app',
  );

}